/**
 * Tickets API Route
 *
 * POST /api/tickets - Create a new ticket
 */

import {
  payloadClient,
  getAuthFromRequest,
  createErrorResponse,
} from "@/lib/payload.server";

export async function POST(request: Request) {
  try {
    const auth = getAuthFromRequest(request);
    const body = await request.json();

    if (!body || typeof body !== "object") {
      return Response.json(
        { error: "Request body is required" },
        { status: 400 },
      );
    }

    // Validate required fields
    if (!body.eventId) {
      return Response.json(
        { error: "eventId is required" },
        { status: 400 },
      );
    }

    // Get current user
    const currentUser = await payloadClient.me<{ id: string; username: string }>(auth);
    
    if (!currentUser) {
      return Response.json(
        { error: "Not authenticated" },
        { status: 401 },
      );
    }

    // Generate unique ticket ID
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 10000).toString().padStart(4, "0");
    const ticketId = `tkt_${timestamp}${random}`;

    // Create ticket data
    const ticketData = {
      id: ticketId,
      event: body.eventId,
      user: currentUser.id,
      paid: body.paid !== undefined ? body.paid : false,
      status: body.status || "valid",
    };

    // The qrToken will be auto-generated by the hook
    const ticket = await payloadClient.create(
      {
        collection: "tickets",
        data: ticketData,
        depth: 2,
      },
      auth,
    );

    return Response.json(ticket, { status: 201 });
  } catch (error) {
    console.error("[API] POST /api/tickets error:", error);
    return createErrorResponse(error);
  }
}
