import type { Comment, Post, Story, StoryItem } from "@/lib/types"

export type { Comment, Post, Story, StoryItem }

export const feedPosts: Post[] = [
  {
    id: "1",
    author: {
      username: "emma.wilson",
      avatar: "https://i.pravatar.cc/150?img=5",
      verified: true,
      name: "Emma Wilson",
    },
    media: [{ type: "image", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800" }],
    caption: "Golden hour magic ✨",
    likes: 2847,
    comments: [],
    timeAgo: "2 hours ago",
    location: "Santa Monica, CA",
  },
  {
    id: "f1",
    author: {
      username: "naturephoto",
      avatar: "https://i.pravatar.cc/150?img=13",
      verified: true,
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800" },
    ],
    caption: "Golden hour in the mountains never disappoints. Nature at its finest.",
    likes: 12847,
    comments: [
      {
        id: "c1",
        username: "urban_explorer",
        avatar: "https://i.pravatar.cc/150?img=8",
        text: "This is absolutely stunning! What camera did you use?",
        timeAgo: "2h",
        likes: 24,
        replies: [
          {
            id: "c1-r1",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "Thanks! Using a Sony A7R IV with a 24-70mm f/2.8",
            timeAgo: "1h",
            likes: 8,
          },
          {
            id: "c1-r2",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Nice! I've been eyeing that lens",
            timeAgo: "1h",
            likes: 3,
          },
          {
            id: "c1-r3",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "Sony makes incredible gear for nature photography",
            timeAgo: "50m",
            likes: 5,
          },
          {
            id: "c1-r4",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "That combo is perfect for landscapes",
            timeAgo: "45m",
            likes: 2,
          },
          {
            id: "c1-r5",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "The dynamic range is unbeatable",
            timeAgo: "30m",
            likes: 6,
          },
        ],
      },
      {
        id: "c2",
        username: "foodie_adventures",
        avatar: "https://i.pravatar.cc/150?img=9",
        text: "The colors are incredible",
        timeAgo: "1h",
        likes: 12,
        replies: [
          {
            id: "c2-r1",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "Thank you! Golden hour magic ✨",
            timeAgo: "55m",
            likes: 4,
          },
          {
            id: "c2-r2",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Mother nature's palette is unmatched",
            timeAgo: "50m",
            likes: 3,
          },
        ],
      },
      {
        id: "c3",
        username: "photo_enthusiast",
        avatar: "https://i.pravatar.cc/150?img=11",
        text: "Which mountain range is this?",
        timeAgo: "3h",
        likes: 18,
        replies: [
          {
            id: "c3-r1",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "This is in the Swiss Alps near Zermatt",
            timeAgo: "2h",
            likes: 12,
          },
          {
            id: "c3-r2",
            username: "photo_enthusiast",
            avatar: "https://i.pravatar.cc/150?img=11",
            text: "Bucket list destination for sure!",
            timeAgo: "2h",
            likes: 5,
          },
          {
            id: "c3-r3",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "I was there last summer, absolutely breathtaking",
            timeAgo: "1h",
            likes: 7,
          },
        ],
      },
      {
        id: "c4",
        username: "landscape_lover",
        avatar: "https://i.pravatar.cc/150?img=14",
        text: "How do you get such sharp images at that focal length?",
        timeAgo: "4h",
        likes: 21,
        replies: [
          {
            id: "c4-r1",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "Tripod is essential! I also use a remote shutter",
            timeAgo: "3h",
            likes: 15,
          },
          {
            id: "c4-r2",
            username: "landscape_lover",
            avatar: "https://i.pravatar.cc/150?img=14",
            text: "Makes sense. Do you bracket exposures?",
            timeAgo: "3h",
            likes: 8,
          },
          {
            id: "c4-r3",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "Yes! Usually 3-5 exposures for HDR",
            timeAgo: "2h",
            likes: 10,
          },
          {
            id: "c4-r4",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Great tip! I need to try this",
            timeAgo: "2h",
            likes: 4,
          },
        ],
      },
      {
        id: "c5",
        username: "mountain_man",
        avatar: "https://i.pravatar.cc/150?img=15",
        text: "The lighting in the second shot is perfection",
        timeAgo: "5h",
        likes: 16,
        replies: [
          {
            id: "c5-r1",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "Right place, right time! 😊",
            timeAgo: "4h",
            likes: 6,
          },
        ],
      },
      {
        id: "c6",
        username: "adventure_seeker",
        avatar: "https://i.pravatar.cc/150?img=10",
        text: "Adding Switzerland to my travel list immediately",
        timeAgo: "6h",
        likes: 9,
      },
    ],
    timeAgo: "2 hours ago",
    location: "Swiss Alps",
  },
  {
    id: "f2",
    author: {
      username: "urban_explorer",
      avatar: "https://i.pravatar.cc/150?img=8",
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800" },
    ],
    caption: "City lights and late nights. The urban jungle comes alive after dark.",
    likes: 8432,
    isNSFW: true,
    comments: [
      {
        id: "c7",
        username: "naturephoto",
        avatar: "https://i.pravatar.cc/150?img=13",
        text: "Love the contrast between these shots!",
        timeAgo: "3h",
        likes: 18,
        replies: [
          {
            id: "c7-r1",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Thanks! Each tells a different story",
            timeAgo: "2h",
            likes: 7,
          },
          {
            id: "c7-r2",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "The third one is my favorite",
            timeAgo: "2h",
            likes: 5,
          },
        ],
      },
      {
        id: "c8",
        username: "night_photography",
        avatar: "https://i.pravatar.cc/150?img=16",
        text: "What ISO were you shooting at?",
        timeAgo: "4h",
        likes: 24,
        replies: [
          {
            id: "c8-r1",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "ISO 3200-6400 range, my Sony handles noise well",
            timeAgo: "3h",
            likes: 16,
          },
          {
            id: "c8-r2",
            username: "night_photography",
            avatar: "https://i.pravatar.cc/150?img=16",
            text: "Clean images for that ISO! Great sensor",
            timeAgo: "3h",
            likes: 9,
          },
          {
            id: "c8-r3",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "I struggle with night shots, any tips?",
            timeAgo: "2h",
            likes: 6,
          },
          {
            id: "c8-r4",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Shoot RAW and use a fast lens, f/1.8 or wider",
            timeAgo: "2h",
            likes: 11,
          },
        ],
      },
      {
        id: "c9",
        username: "cityscape_fan",
        avatar: "https://i.pravatar.cc/150?img=17",
        text: "Tokyo is such a photographer's dream",
        timeAgo: "5h",
        likes: 31,
        replies: [
          {
            id: "c9-r1",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Every corner is a potential shot",
            timeAgo: "4h",
            likes: 14,
          },
          {
            id: "c9-r2",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "Going there next month, any location tips?",
            timeAgo: "4h",
            likes: 8,
          },
          {
            id: "c9-r3",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Shibuya crossing at night is a must!",
            timeAgo: "3h",
            likes: 12,
          },
        ],
      },
      {
        id: "c10",
        username: "architect_lens",
        avatar: "https://i.pravatar.cc/150?img=18",
        text: "The architectural lines in shot 4 are 🔥",
        timeAgo: "6h",
        likes: 19,
        replies: [
          {
            id: "c10-r1",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Thanks! Tokyo's modern architecture is inspiring",
            timeAgo: "5h",
            likes: 8,
          },
          {
            id: "c10-r2",
            username: "architect_lens",
            avatar: "https://i.pravatar.cc/150?img=18",
            text: "The symmetry is perfect",
            timeAgo: "5h",
            likes: 4,
          },
        ],
      },
      {
        id: "c11",
        username: "street_photo_daily",
        avatar: "https://i.pravatar.cc/150?img=19",
        text: "Your composition skills are incredible",
        timeAgo: "7h",
        likes: 28,
        replies: [
          {
            id: "c11-r1",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Appreciate that! Still learning every day",
            timeAgo: "6h",
            likes: 10,
          },
        ],
      },
      {
        id: "c12",
        username: "neon_nights",
        avatar: "https://i.pravatar.cc/150?img=20",
        text: "The neon reflections in the second photo 😍",
        timeAgo: "8h",
        likes: 22,
      },
    ],
    timeAgo: "5 hours ago",
    location: "Tokyo, Japan",
  },
  {
    id: "f3",
    author: {
      username: "foodie_adventures",
      avatar: "https://i.pravatar.cc/150?img=9",
      verified: true,
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800" },
    ],
    caption: "When food becomes art. This dish was an absolute masterpiece.",
    likes: 5621,
    comments: [
      {
        id: "c13",
        username: "travel_with_me",
        avatar: "https://i.pravatar.cc/150?img=10",
        text: "Adding this place to my list!",
        timeAgo: "5h",
        likes: 8,
        replies: [
          {
            id: "c13-r1",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "You won't regret it! Book in advance",
            timeAgo: "4h",
            likes: 5,
          },
          {
            id: "c13-r2",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "Thanks for the tip!",
            timeAgo: "4h",
            likes: 2,
          },
        ],
      },
      {
        id: "c14",
        username: "chef_life",
        avatar: "https://i.pravatar.cc/150?img=21",
        text: "The plating technique is phenomenal",
        timeAgo: "6h",
        likes: 34,
        replies: [
          {
            id: "c14-r1",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "The chef is a true artist!",
            timeAgo: "5h",
            likes: 12,
          },
          {
            id: "c14-r2",
            username: "chef_life",
            avatar: "https://i.pravatar.cc/150?img=21",
            text: "Which restaurant is this?",
            timeAgo: "5h",
            likes: 8,
          },
          {
            id: "c14-r3",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "L'Atelier in Paris, Michelin 3-star",
            timeAgo: "4h",
            likes: 15,
          },
          {
            id: "c14-r4",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "On my bucket list!",
            timeAgo: "4h",
            likes: 6,
          },
        ],
      },
      {
        id: "c15",
        username: "food_photography",
        avatar: "https://i.pravatar.cc/150?img=22",
        text: "What lighting setup do you use for food shots?",
        timeAgo: "7h",
        likes: 41,
        replies: [
          {
            id: "c15-r1",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "Natural window light when possible, diffused flash otherwise",
            timeAgo: "6h",
            likes: 18,
          },
          {
            id: "c15-r2",
            username: "food_photography",
            avatar: "https://i.pravatar.cc/150?img=22",
            text: "The soft lighting really makes the textures pop",
            timeAgo: "6h",
            likes: 9,
          },
          {
            id: "c15-r3",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "Thanks! I use a 50mm f/1.4 for these shots",
            timeAgo: "5h",
            likes: 14,
          },
        ],
      },
      {
        id: "c16",
        username: "restaurant_critic",
        avatar: "https://i.pravatar.cc/150?img=23",
        text: "How was the taste compared to the presentation?",
        timeAgo: "8h",
        likes: 27,
        replies: [
          {
            id: "c16-r1",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "Even better than it looks! Every bite was perfect",
            timeAgo: "7h",
            likes: 16,
          },
          {
            id: "c16-r2",
            username: "restaurant_critic",
            avatar: "https://i.pravatar.cc/150?img=23",
            text: "High praise! Worth the price?",
            timeAgo: "7h",
            likes: 11,
          },
          {
            id: "c16-r3",
            username: "foodie_adventures",
            avatar: "https://i.pravatar.cc/150?img=9",
            text: "Special occasion worthy",
            timeAgo: "6h",
            likes: 13,
          },
        ],
      },
      {
        id: "c17",
        username: "paris_foodie",
        avatar: "https://i.pravatar.cc/150?img=24",
        text: "I live in Paris and still haven't been here 🙈",
        timeAgo: "9h",
        likes: 19,
      },
      {
        id: "c18",
        username: "michelin_hunter",
        avatar: "https://i.pravatar.cc/150?img=25",
        text: "The tasting menu here is legendary",
        timeAgo: "10h",
        likes: 23,
      },
    ],
    timeAgo: "8 hours ago",
    location: "Paris, France",
  },
  {
    id: "f4",
    author: {
      username: "travel_with_me",
      avatar: "https://i.pravatar.cc/150?img=10",
    },
    media: [
      { type: "video", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4" },
      { type: "image", url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800" },
    ],
    caption: "Paradise found. Sometimes you just need to disconnect to reconnect.",
    likes: 23156,
    comments: [
      {
        id: "c19",
        username: "naturephoto",
        avatar: "https://i.pravatar.cc/150?img=13",
        text: "Dream destination! How long did you stay?",
        timeAgo: "10h",
        likes: 32,
        replies: [
          {
            id: "c19-r1",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "10 days! Not nearly enough time",
            timeAgo: "9h",
            likes: 18,
          },
          {
            id: "c19-r2",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "I could spend a month there!",
            timeAgo: "9h",
            likes: 12,
          },
          {
            id: "c19-r3",
            username: "urban_explorer",
            avatar: "https://i.pravatar.cc/150?img=8",
            text: "Which resort did you stay at?",
            timeAgo: "8h",
            likes: 9,
          },
          {
            id: "c19-r4",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "Soneva Fushi, highly recommend!",
            timeAgo: "8h",
            likes: 15,
          },
        ],
      },
      {
        id: "c20",
        username: "urban_explorer",
        avatar: "https://i.pravatar.cc/150?img=8",
        text: "The drone footage must be amazing!",
        timeAgo: "9h",
        likes: 15,
        replies: [
          {
            id: "c20-r1",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "Shot some incredible 4K footage!",
            timeAgo: "8h",
            likes: 11,
          },
          {
            id: "c20-r2",
            username: "drone_pilot",
            avatar: "https://i.pravatar.cc/150?img=16",
            text: "Which drone are you using?",
            timeAgo: "8h",
            likes: 7,
          },
          {
            id: "c20-r3",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "DJI Mavic 3 Pro",
            timeAgo: "7h",
            likes: 9,
          },
        ],
      },
      {
        id: "c21",
        username: "beach_lover",
        avatar: "https://i.pravatar.cc/150?img=26",
        text: "The water color is unreal!",
        timeAgo: "11h",
        likes: 28,
        replies: [
          {
            id: "c21-r1",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "Crystal clear turquoise, no filter needed!",
            timeAgo: "10h",
            likes: 14,
          },
          {
            id: "c21-r2",
            username: "naturephoto",
            avatar: "https://i.pravatar.cc/150?img=13",
            text: "Maldives water is something else",
            timeAgo: "10h",
            likes: 8,
          },
        ],
      },
      {
        id: "c22",
        username: "honeymoon_planning",
        avatar: "https://i.pravatar.cc/150?img=20",
        text: "Saving this for honeymoon inspiration!",
        timeAgo: "12h",
        likes: 24,
        replies: [
          {
            id: "c22-r1",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "Perfect honeymoon destination! Congratulations!",
            timeAgo: "11h",
            likes: 12,
          },
          {
            id: "c22-r2",
            username: "honeymoon_planning",
            avatar: "https://i.pravatar.cc/150?img=20",
            text: "Thank you! Any resort recommendations?",
            timeAgo: "11h",
            likes: 6,
          },
          {
            id: "c22-r3",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "DM me, I have a whole list!",
            timeAgo: "10h",
            likes: 10,
          },
        ],
      },
      {
        id: "c23",
        username: "scuba_diver",
        avatar: "https://i.pravatar.cc/150?img=18",
        text: "Did you go diving? The reefs there are incredible",
        timeAgo: "13h",
        likes: 31,
        replies: [
          {
            id: "c23-r1",
            username: "travel_with_me",
            avatar: "https://i.pravatar.cc/150?img=10",
            text: "Yes! Saw manta rays and whale sharks",
            timeAgo: "12h",
            likes: 22,
          },
          {
            id: "c23-r2",
            username: "scuba_diver",
            avatar: "https://i.pravatar.cc/150?img=18",
            text: "So jealous! That's on my dive bucket list",
            timeAgo: "12h",
            likes: 13,
          },
        ],
      },
      {
        id: "c24",
        username: "sunset_chaser",
        avatar: "https://i.pravatar.cc/150?img=27",
        text: "That sunset in pic 3 is breathtaking",
        timeAgo: "14h",
        likes: 19,
      },
    ],
    timeAgo: "3 hours ago",
    location: "Maldives",
  },
  {
    id: "f5",
    author: {
      username: "nature_lover",
      avatar: "https://i.pravatar.cc/150?img=28",
      verified: true,
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800" },
    ],
    caption: "Spring in the mountains. Flowers and wildlife at their peak.",
    likes: 19876,
    isNSFW: true,
    comments: [
      {
        id: "c25",
        username: "photo_enthusiast",
        avatar: "https://i.pravatar.cc/150?img=11",
        text: "Absolutely breathtaking!",
        timeAgo: "1h",
        likes: 34,
        replies: [
          {
            id: "c25-r1",
            username: "nature_lover",
            avatar: "https://i.pravatar.cc/150?img=28",
            text: "Thanks! Spring is always magical",
            timeAgo: "45m",
            likes: 16,
          },
          {
            id: "c25-r2",
            username: "landscape_lover",
            avatar: "https://i.pravatar.cc/150?img=14",
            text: "The macro shot is stunning",
            timeAgo: "40m",
            likes: 9,
          },
        ],
      },
      {
        id: "c26",
        username: "wildlife_fan",
        avatar: "https://i.pravatar.cc/150?img=29",
        text: "Love the wildlife shots!",
        timeAgo: "2h",
        likes: 28,
        replies: [
          {
            id: "c26-r1",
            username: "nature_lover",
            avatar: "https://i.pravatar.cc/150?img=28",
            text: "Thanks! Capturing life in the wild is my passion",
            timeAgo: "1h",
            likes: 12,
          },
        ],
      },
      {
        id: "c27",
        username: "flower_photography",
        avatar: "https://i.pravatar.cc/150?img=30",
        text: "The flower macro is amazing",
        timeAgo: "3h",
        likes: 42,
        replies: [
          {
            id: "c27-r1",
            username: "nature_lover",
            avatar: "https://i.pravatar.cc/150?img=28",
            text: "Thank you! Macro photography is so rewarding",
            timeAgo: "2h",
            likes: 18,
          },
        ],
      },
    ],
    timeAgo: "1 hour ago",
    location: "Yellowstone National Park",
  },
  {
    id: "f6",
    author: {
      username: "travel_with_me",
      avatar: "https://i.pravatar.cc/150?img=10",
      verified: true,
      name: "Sarah Anderson",
    },
    media: [
      { type: "video", url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" },
    ],
    caption: "Behind the scenes of our latest project. The magic happens when nobody's watching.",
    likes: 18924,
    comments: [],
    timeAgo: "3 hours ago",
    location: "Los Angeles",
  },
  {
    id: "f7",
    author: {
      username: "coffee_culture",
      avatar: "https://i.pravatar.cc/150?img=31",
      verified: false,
      name: "Marcus Chen",
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800" },
    ],
    caption: "Morning ritual ☕ Nothing beats a perfectly pulled espresso to start the day.",
    likes: 4532,
    comments: [
      {
        id: "c28",
        username: "foodie_adventures",
        avatar: "https://i.pravatar.cc/150?img=9",
        text: "That crema looks perfect!",
        timeAgo: "1h",
        likes: 18,
        replies: [
          {
            id: "c28-r1",
            username: "coffee_culture",
            avatar: "https://i.pravatar.cc/150?img=31",
            text: "Thanks! Took me months to master the technique",
            timeAgo: "45m",
            likes: 8,
          },
        ],
      },
      {
        id: "c29",
        username: "barista_life",
        avatar: "https://i.pravatar.cc/150?img=32",
        text: "What beans are you using?",
        timeAgo: "2h",
        likes: 24,
        replies: [
          {
            id: "c29-r1",
            username: "coffee_culture",
            avatar: "https://i.pravatar.cc/150?img=31",
            text: "Ethiopian Yirgacheffe, light roast",
            timeAgo: "1h",
            likes: 14,
          },
        ],
      },
    ],
    timeAgo: "4 hours ago",
    location: "Brooklyn, NY",
  },
  {
    id: "f8",
    author: {
      username: "street_style",
      avatar: "https://i.pravatar.cc/150?img=33",
      verified: true,
      name: "Olivia Park",
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800" },
    ],
    caption: "New collection drop 🔥 Link in bio. Limited pieces available.",
    likes: 34521,
    isNSFW: false,
    comments: [
      {
        id: "c30",
        username: "fashion_forward",
        avatar: "https://i.pravatar.cc/150?img=34",
        text: "NEED that jacket! 😍",
        timeAgo: "30m",
        likes: 89,
        replies: [
          {
            id: "c30-r1",
            username: "street_style",
            avatar: "https://i.pravatar.cc/150?img=33",
            text: "Only 50 made! Hurry!",
            timeAgo: "20m",
            likes: 42,
          },
        ],
      },
      {
        id: "c31",
        username: "urban_explorer",
        avatar: "https://i.pravatar.cc/150?img=8",
        text: "The styling is impeccable",
        timeAgo: "1h",
        likes: 56,
      },
    ],
    timeAgo: "1 hour ago",
    location: "Seoul, South Korea",
  },
  {
    id: "f9",
    author: {
      username: "astro_captures",
      avatar: "https://i.pravatar.cc/150?img=35",
      verified: true,
      name: "David Starr",
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800" },
    ],
    caption: "Milky Way season is here 🌌 3 hours of exposure, 200 stacked images.",
    likes: 67234,
    comments: [
      {
        id: "c32",
        username: "naturephoto",
        avatar: "https://i.pravatar.cc/150?img=13",
        text: "This is absolutely incredible! What tracker are you using?",
        timeAgo: "2h",
        likes: 156,
        replies: [
          {
            id: "c32-r1",
            username: "astro_captures",
            avatar: "https://i.pravatar.cc/150?img=35",
            text: "Sky-Watcher Star Adventurer GTi. Game changer!",
            timeAgo: "1h",
            likes: 78,
          },
          {
            id: "c32-r2",
            username: "photo_enthusiast",
            avatar: "https://i.pravatar.cc/150?img=11",
            text: "Adding that to my wishlist",
            timeAgo: "45m",
            likes: 23,
          },
        ],
      },
      {
        id: "c33",
        username: "space_nerd",
        avatar: "https://i.pravatar.cc/150?img=36",
        text: "Is that Andromeda in the second shot?",
        timeAgo: "3h",
        likes: 89,
        replies: [
          {
            id: "c33-r1",
            username: "astro_captures",
            avatar: "https://i.pravatar.cc/150?img=35",
            text: "Good eye! Yes it is, about 2.5 million light years away",
            timeAgo: "2h",
            likes: 67,
          },
        ],
      },
    ],
    timeAgo: "6 hours ago",
    location: "Death Valley, CA",
  },
  {
    id: "f10",
    author: {
      username: "pet_paradise",
      avatar: "https://i.pravatar.cc/150?img=37",
      verified: false,
      name: "Luna & Max",
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=800" },
    ],
    caption: "Beach day with my best friends 🐕 They were SO happy!",
    likes: 28943,
    comments: [
      {
        id: "c34",
        username: "dog_lover_99",
        avatar: "https://i.pravatar.cc/150?img=38",
        text: "OMG they are adorable!! What breeds?",
        timeAgo: "1h",
        likes: 234,
        replies: [
          {
            id: "c34-r1",
            username: "pet_paradise",
            avatar: "https://i.pravatar.cc/150?img=37",
            text: "Luna is a Golden Retriever, Max is a Border Collie mix!",
            timeAgo: "45m",
            likes: 89,
          },
        ],
      },
      {
        id: "c35",
        username: "beach_vibes",
        avatar: "https://i.pravatar.cc/150?img=39",
        text: "Which beach is this? Need to take my pup!",
        timeAgo: "2h",
        likes: 45,
        replies: [
          {
            id: "c35-r1",
            username: "pet_paradise",
            avatar: "https://i.pravatar.cc/150?img=37",
            text: "Huntington Dog Beach! It's off-leash",
            timeAgo: "1h",
            likes: 32,
          },
        ],
      },
    ],
    timeAgo: "5 hours ago",
    location: "Huntington Beach, CA",
  },
  {
    id: "f11",
    author: {
      username: "minimalist_home",
      avatar: "https://i.pravatar.cc/150?img=40",
      verified: true,
      name: "Interior Studio",
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800" },
      { type: "image", url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800" },
    ],
    caption: "Less is more. Our latest project - a Scandinavian-inspired living space.",
    likes: 15678,
    comments: [
      {
        id: "c36",
        username: "design_daily",
        avatar: "https://i.pravatar.cc/150?img=41",
        text: "The natural light in this space is everything",
        timeAgo: "3h",
        likes: 67,
        replies: [
          {
            id: "c36-r1",
            username: "minimalist_home",
            avatar: "https://i.pravatar.cc/150?img=40",
            text: "We knocked out a wall to add those floor-to-ceiling windows!",
            timeAgo: "2h",
            likes: 34,
          },
        ],
      },
    ],
    timeAgo: "7 hours ago",
    location: "Copenhagen, Denmark",
  },
  {
    id: "f12",
    author: {
      username: "vinyl_vibes",
      avatar: "https://i.pravatar.cc/150?img=42",
      verified: false,
      name: "Record Collector",
    },
    media: [
      { type: "image", url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=800" },
    ],
    caption: "Finally found a mint condition pressing 🎵 The hunt is half the fun.",
    likes: 3421,
    comments: [
      {
        id: "c37",
        username: "music_junkie",
        avatar: "https://i.pravatar.cc/150?img=43",
        text: "What a find! How much did you pay?",
        timeAgo: "4h",
        likes: 28,
        replies: [
          {
            id: "c37-r1",
            username: "vinyl_vibes",
            avatar: "https://i.pravatar.cc/150?img=42",
            text: "Got lucky, only $45 at a local shop!",
            timeAgo: "3h",
            likes: 19,
          },
        ],
      },
    ],
    timeAgo: "9 hours ago",
    location: "Austin, TX",
  },
]

export const profilePosts: Post[] = feedPosts

export const posts: Post[] = feedPosts

export function getPostById(id: string): Post | undefined {
  return feedPosts.find((post) => post.id === id)
}

export const storiesData: Story[] = [
  {
    id: "your-story",
    username: "Your story",
    avatar: "https://i.pravatar.cc/150?img=12",
    hasStory: false,
    isViewed: false,
    isYou: true,
    stories: [],
  },
  {
    id: "1",
    username: "emma_w",
    avatar: "https://i.pravatar.cc/150?img=5",
    hasStory: true,
    isViewed: false,
    stories: [
      {
        url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "emma_w",
          subheading: "2h ago",
          profileImage: "https://i.pravatar.cc/150?img=5",
        },
      },
      {
        url: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        type: "video",
        duration: 15000,
        header: {
          heading: "emma_w",
          subheading: "2h ago",
          profileImage: "https://i.pravatar.cc/150?img=5",
        },
      },
      {
        url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "emma_w",
          subheading: "2h ago",
          profileImage: "https://i.pravatar.cc/150?img=5",
        },
      },
    ],
  },
  {
    id: "2",
    username: "alex.dev",
    avatar: "https://i.pravatar.cc/150?img=13",
    hasStory: true,
    isViewed: false,
    stories: [
      {
        url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "alex.dev",
          subheading: "4h ago",
          profileImage: "https://i.pravatar.cc/150?img=13",
        },
      },
      {
        url: "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        type: "video",
        duration: 15000,
        header: {
          heading: "alex.dev",
          subheading: "4h ago",
          profileImage: "https://i.pravatar.cc/150?img=13",
        },
      },
    ],
  },
  {
    id: "3",
    username: "sarah.art",
    avatar: "https://i.pravatar.cc/150?img=14",
    hasStory: true,
    isViewed: true,
    stories: [
      {
        url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "sarah.art",
          subheading: "6h ago",
          profileImage: "https://i.pravatar.cc/150?img=14",
        },
      },
      {
        url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "sarah.art",
          subheading: "6h ago",
          profileImage: "https://i.pravatar.cc/150?img=14",
        },
      },
    ],
  },
  {
    id: "4",
    username: "mike_photo",
    avatar: "https://i.pravatar.cc/150?img=15",
    hasStory: true,
    isViewed: false,
    stories: [
      {
        url: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        type: "video",
        duration: 15000,
        header: {
          heading: "mike_photo",
          subheading: "8h ago",
          profileImage: "https://i.pravatar.cc/150?img=15",
        },
      },
      {
        url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "mike_photo",
          subheading: "8h ago",
          profileImage: "https://i.pravatar.cc/150?img=15",
        },
      },
    ],
  },
  {
    id: "5",
    username: "lisa.music",
    avatar: "https://i.pravatar.cc/150?img=16",
    hasStory: true,
    isViewed: true,
    stories: [
      {
        url: "https://images.unsplash.com/photo-1517245386807-8f0f3e531c6a?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "lisa.music",
          subheading: "12h ago",
          profileImage: "https://i.pravatar.cc/150?img=16",
        },
      },
    ],
  },
  {
    id: "6",
    username: "john_fit",
    avatar: "https://i.pravatar.cc/150?img=17",
    hasStory: true,
    isViewed: false,
    stories: [
      {
        url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "john_fit",
          subheading: "14h ago",
          profileImage: "https://i.pravatar.cc/150?img=17",
        },
      },
    ],
  },
  {
    id: "7",
    username: "amy.cook",
    avatar: "https://i.pravatar.cc/150?img=18",
    hasStory: true,
    isViewed: true,
    stories: [
      {
        url: "https://images.unsplash.com/photo-1512621776950-296cd0d26b37?w=800",
        type: "image",
        duration: 5000,
        header: {
          heading: "amy.cook",
          subheading: "16h ago",
          profileImage: "https://i.pravatar.cc/150?img=18",
        },
      },
    ],
  },
]
