-- Story animated GIF overlays
-- Additive only: stores normalized Klipy GIF sticker overlays for published stories.

CREATE TABLE IF NOT EXISTS public.stories_stickers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id bigint NOT NULL REFERENCES public.stories(id) ON DELETE CASCADE,
  asset_url text NOT NULL,
  position_x double precision NOT NULL DEFAULT 0.5,
  position_y double precision NOT NULL DEFAULT 0.5,
  size_ratio double precision NOT NULL DEFAULT 0.2,
  scale double precision NOT NULL DEFAULT 1,
  rotation double precision NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.stories_stickers
  ADD COLUMN IF NOT EXISTS story_id bigint,
  ADD COLUMN IF NOT EXISTS asset_url text,
  ADD COLUMN IF NOT EXISTS position_x double precision NOT NULL DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS position_y double precision NOT NULL DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS size_ratio double precision NOT NULL DEFAULT 0.2,
  ADD COLUMN IF NOT EXISTS scale double precision NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS rotation double precision NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'stories_stickers_story_id_fkey'
  ) THEN
    ALTER TABLE public.stories_stickers
      ADD CONSTRAINT stories_stickers_story_id_fkey
      FOREIGN KEY (story_id)
      REFERENCES public.stories(id)
      ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_stories_stickers_story_id
  ON public.stories_stickers (story_id);

GRANT ALL ON public.stories_stickers TO service_role;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relkind = 'S'
      AND relname = 'stories_stickers_id_seq'
  ) THEN
    GRANT USAGE, SELECT ON SEQUENCE public.stories_stickers_id_seq TO service_role;
  END IF;
END $$;
