/**
 * DATABASE SCHEMA MAPPING
 * This file maps actual Supabase table/column names to app-friendly names
 * Based on introspected schema from Supabase database
 */

export const DB = {
  users: {
    table: 'users',
    id: 'id',
    username: 'username',
    email: 'email',
    firstName: 'first_name',
    lastName: 'last_name',
    avatarId: 'avatar_id',
    bio: 'bio',
    location: 'location',
    verified: 'verified',
    followersCount: 'followers_count',
    followingCount: 'following_count',
    postsCount: 'posts_count',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    isPrivate: 'is_private',
  },
  posts: {
    table: 'posts',
    id: 'id',
    authorId: 'author_id',
    content: 'content',
    location: 'location',
    likesCount: 'likes_count',
    commentsCount: 'comments_count',
    bookmarksCount: 'bookmarks_count',
    visibility: 'visibility',
    isNsfw: 'is_nsfw',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  postsMedia: {
    table: 'posts_media',
    id: 'id',
    parentId: '_parent_id',
    type: 'type',
    url: 'url',
    imageId: 'image_id',
    order: '_order',
  },
  stories: {
    table: 'stories',
    id: 'id',
    authorId: 'author_id',
    mediaId: 'media_id',
    caption: 'caption',
    location: 'location',
    visibility: 'visibility',
    expiresAt: 'expires_at',
    viewCount: 'view_count',
    viewersCount: 'viewers_count',
    createdAt: 'created_at',
  },
  likes: {
    table: 'likes',
    id: 'id',
    userId: 'user_id',
    postId: 'post_id',
    createdAt: 'created_at',
  },
  comments: {
    table: 'comments',
    id: 'id',
    postId: 'post_id',
    authorId: 'author_id',
    content: 'content',
    likesCount: 'likes_count',
    createdAt: 'created_at',
  },
  follows: {
    table: 'follows',
    id: 'id',
    followerId: 'follower_id',
    followingId: 'following_id',
    createdAt: 'created_at',
  },
  bookmarks: {
    table: 'bookmarks',
    id: 'id',
    userId: 'user_id',
    postId: 'post_id',
    createdAt: 'created_at',
  },
  notifications: {
    table: 'notifications',
    id: 'id',
    recipientId: 'recipient_id',
    actorId: 'actor_id',
    type: 'type',
    read: 'read',
    createdAt: 'created_at',
  },
  events: {
    table: 'events',
    id: 'id',
    hostId: 'host_id',
    title: 'title',
    description: 'description',
    startDate: 'start_date',
    endDate: 'end_date',
    location: 'location',
    coverImageUrl: 'cover_image_url',
    price: 'price',
    maxAttendees: 'max_attendees',
    totalAttendees: 'total_attendees',
    isOnline: 'is_online',
    createdAt: 'created_at',
  },
  eventRsvps: {
    table: 'event_rsvps',
    id: 'id',
    eventId: 'event_id',
    userId: 'user_id',
    status: 'status',
    createdAt: 'created_at',
  },
  conversations: {
    table: 'conversations',
    id: 'id',
    isGroup: 'is_group',
    groupName: 'group_name',
    lastMessageAt: 'last_message_at',
    createdAt: 'created_at',
  },
  conversationsRels: {
    table: 'conversations_rels',
    parentId: 'parent_id',
    usersId: 'users_id',
  },
  messages: {
    table: 'messages',
    id: 'id',
    conversationId: 'conversation_id',
    senderId: 'sender_id',
    content: 'content',
    read: 'read',
    createdAt: 'created_at',
  },
  media: {
    table: 'media',
    id: 'id',
    url: 'url',
    filename: 'filename',
    mimeType: 'mime_type',
    filesize: 'filesize',
    width: 'width',
    height: 'height',
    ownerId: 'owner_id',
    createdAt: 'created_at',
  },
} as const;
